device: cuda
train:
  batch_size: 512
  train_epochs: 40
  loss:
    - crossentropyloss
  optim:
    name: adam
    learning_rate: 0.001
    others:
      betas: [0.9, 0.999]
  lr_scheduler:
    name: multisteplr
    others:
      milestones: [20, 30]
      gamma: 0.1
  model_path: ./pretrained
  progress_path: ./train_progress
  plot_epochs: 5
model:
  device: cuda
  patch_size: 2
  in_channels: 3
  hidden_dim: 128
  num_heads: 4
  feedforward_dim: 512
  num_layers: 12
  dropout_rate: 0.1
  num_patches: 256
  num_classes: 1000
test:
  batch_size: 256
